(define (make-point x y) (cons x y))
(define (x-point p) (car p))
(define (y-point p) (cdr p))

(define (make-segment a b) (cons a b))
(define (start-segment l) (car l))
(define (end-segment l) (cdr l))

(define (print-point p)
    ;(newline)
    (display "(")
    (display (x-point p))
    (display ", ")
    (display (y-point p))
    (display ")"))

; (define (print-segment l)
;     ;(newline)
;     (display "[")
;     (display (print-point (start-segment l)))
;     (display ", ")
;     (display (print-point (end-segment l)))
;     (display "]"))

(define (midpoint-segment l)
    (define (average a b) (/ (+ a b) 2.0))
    (make-point (average (x-point (start-segment l))
                         (x-point (end-segment l)))
                (average (y-point (start-segment l))
                         (y-point (end-segment l)))))

(define a (make-point 1 2))
(define b (make-point 4 5))
(define l (make-segment a b))
(print-point a)
(print-point (midpoint-segment l))
