(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch pass m)
    (if (not (eq? pass passwd))
        (lambda (xx) "Incorrect passwd")
        (cond ((eq? m 'withdraw ) withdraw)
              ((eq? m 'deposit ) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                          m)))))
  dispatch)

(define acc (make-account 100 'hange ))
((acc 'hange 'withdraw ) 10)
((acc 'hange 'deposit ) 1000)
((acc 'haha 'withdraw ) 10)
